M48
; DRILL file {KiCad 9.0.3} date 2025-11-21T22:03:19+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-21T22:03:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.300
%
G90
G05
T1
X152.5Y-139.5
X152.5Y-160.5
X287.5Y-139.5
X287.5Y-160.5
T2
X191.0Y-142.03
X253.0Y-142.03
T3
X55.0Y-90.0
X55.0Y-210.0
X290.0Y-90.0
X290.0Y-210.0
M30
